function [varParams, modelParams, spec] = validationSetA(subSet)
%validatinoSetA Define validation parameter set A for the VCO-ADC model. 
% For use with the specific model evaluateAdcModelA.m
%%   INPUT:
%       subSet : Integer
%           Selects the subSet of variables, used to toggle between
%           validation and optimization
%           subSet = 0 --> Validation
%           subSet = 1 --> Optimization
%%   OUTPUT : 
% This function returns all configuration structures required to run
% validation and optimization for the analytical VCO-ADC model. It allows 
% clean, easily reproducible, swappable and expandable validation setups.
% The configuration is split into three logical groups:
%
%   1) varParams   : Design variables and their constraints
%   2) modelParams : ADC model configuration
%   3) spec        : Target ADC performance specifications

%% ------------------------------------------------------------------------
% Variable parameters 
% -------------------------------------------------------------------------

% Sampling frequency
varParams(1) = struct( ...
    'name', 'fs', ...
    'range', [1e3, 512e3], ...
    'bounds', [1e3, 512e3], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 32e3);

if (~subSet)
    % VCO gain : Fixed - For Validation
    varParams(2) = struct( ...
        'name', 'kVco', ...
        'range', [10e6, 500e6], ...
        'bounds', [10e6, 500e6], ...
        'analysisType', 'fixed', ...
        'sweepType', '', ...
        'sweepLength', '', ...
        'fixedValue', 120e6);
else
    % VCO gain : Surface - For Optimization
    varParams(2) = struct( ...
        'name', 'kVco', ...
        'range', [50e6, 400e6], ...
        'bounds', [50e6, 400e6], ...
        'analysisType', 'surface', ...
        'sweepType', 'lin', ...
        'sweepLength', 50, ...
        'fixedValue', 120e6);
end

if(~subSet)
    % Full-scale DAC voltage : Fixed - For Validation
    varParams(3) = struct( ...
        'name', 'vdacFs', ...
        'range', [0.2, 1.8], ...
        'bounds', [0.2, 1.8], ...
        'analysisType', 'fixed', ...
        'sweepType', '', ...
        'sweepLength', '', ...
        'fixedValue', 1.2);
else   
    % Full-scale DAC voltage : Surface - For Optimization
    varParams(3) = struct( ...
        'name', 'vdacFs', ...
        'range', [0.2, 1.8], ...
        'bounds', [0.2, 1.8], ...
        'analysisType', 'surface', ...
        'sweepType', 'lin', ...
        'sweepLength', 50, ...
        'fixedValue', 1.2);
end

% DAC resolution
varParams(4) = struct( ...
    'name', 'nDac', ...
    'range', [6, 16], ...
    'bounds', [6, 16], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 9);

% Input resistance
varParams(5) = struct( ...
    'name', 'f_{ch}', ...
    'range', [1e3, 512e3], ...
    'bounds', [1e3, 512e3], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 32e3);

% Input resistance
varParams(6) = struct( ...
    'name', 'C_{IN}', ...
    'range', [0.5e-12, 20e-12], ...
    'bounds', [0.5e-12, 30e-12], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 20.66e-12);

%% ------------------------------------------------------------------------
% ADC model parameters
% -------------------------------------------------------------------------

modelParams = struct();

% -------------------- System --------------------
modelParams.loopOrder          = 1;
modelParams.nef                = 4;
modelParams.maxFoM             = 200;
modelParams.noiseFoldingEnable = 1;
modelParams.fsRes              = 50000;
modelParams.bwIterMethod       = 'fixed';
modelParams.bwIterations       = 5;

% -------------------- Input --------------------
modelParams.maxVinFs  = 0.6;
modelParams.inputFreq = 86;
modelParams.minOsr    = 2;
modelParams.rpErr = 10e9;

% -------------------- Quantizer --------------------
modelParams.nMp  = 1; 

% -------------------- SFDR --------------------
modelParams.a1 = 1;
modelParams.a2 = 397*5.2e-6;
modelParams.a3 = 397*10;

% -------------------- DAC --------------------
modelParams.cdacTot = 2e-12;
modelParams.sigmaC   = 0.6/100;
modelParams.maxVdd   = 1.8;
modelParams.maxVinFs = 0.6;

% -------------------- Power --------------------
modelParams.vddAfe    = 1.2;
modelParams.vddDig    = 0.7;
modelParams.pVcoRef   = 0.44e-6;
modelParams.kVcoRef   = 120e6;
modelParams.pDigRef   = 0.84e-6;
modelParams.fsRef     = 32e3;
modelParams.vddDigRef = 0.7;
modelParams.T = 300;
modelParams.phiT = 0.025;
%% ------------------------------------------------------------------------
% ADC performance specifications
% -------------------------------------------------------------------------

spec = struct( ...
    'FOM',      180, ...
    'SNDR',     80, ...
    'P_TOT',    10e-6, ...
    'BW',       1e3, ...
    'IRN_FLOOR', 250e-9, ...
    'VIN_FS',    0.2, ...
    'RIN',1e6, ...
    'BW_LOW',10);

end
