function [varParams, modelParams, spec] = validationSetB(subSet)
%validatinoSetB Define validation parameter set B for the VCO-ADC model. 
% For use with the specific model evaluateAdcModelB.m
%%   INPUT:
%       subSet : Integer
%           Selects the subSet of variables, used to toggle between
%           validation and optimization
%           subSet = 0 --> Validation
%           subSet = 1 --> Optimization
%%   OUTPUT : 
% This function returns all configuration structures required to run
% validation and optimization for the analytical VCO-ADC model. It allows 
% clean, easily reproducible, swappable and expandable validation setups.
% The configuration is split into three logical groups:
%
%   1) varParams   : Design variables and their constraints
%   2) modelParams : ADC model configuration
%   3) spec        : Target ADC performance specifications

%% ------------------------------------------------------------------------
% Variable parameters 
% -------------------------------------------------------------------------

% Sampling frequency
varParams(1) = struct( ...
    'name', 'fs', ...
    'range', [100e6, 500e6], ...
    'bounds', [100e6, 500e6], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 300e6);

if(~subSet)
    % VCO gain : Fixed - For Validation
    varParams(2) = struct( ...
        'name', 'kVco', ...
        'range', [1e9, 500e9], ...
        'bounds', [1e9, 500e9], ...
        'analysisType', 'fixed', ...
        'sweepType', '', ...
        'sweepLength', '', ...
        'fixedValue', 200e9);
else
    % VCO gain : Surface - For Optimization
    varParams(2) = struct( ...
        'name', 'kVco', ...
        'range', [10e9, 400e9], ...
        'bounds', [10e9, 400e9], ...
        'analysisType', 'surface', ...
        'sweepType', 'lin', ...
        'sweepLength', 50, ...
        'fixedValue', 200e9);
end

if(~subSet)
    % Full-scale input voltage : Fixed
    varParams(3) = struct( ...
        'name', 'vinFs', ...
        'range', [1.2, 3.6], ...
        'bounds', [1.2, 3.6], ...
        'analysisType', 'fixed', ...
        'sweepType', '', ...
        'sweepLength', '', ...
        'fixedValue', 2.4);
else
    % Full-scale input voltage : Surface
    varParams(3) = struct( ...
        'name', 'vinFs', ...
        'range', [1.2, 3], ...
        'bounds', [1.2, 3], ...
        'analysisType', 'surface', ...
        'sweepType', 'lin', ...
        'sweepLength', 50, ...
        'fixedValue', 2.4);
end

% DAC resolution
varParams(4) = struct( ...
    'name', 'nDac', ...
    'range', [16, 32], ...
    'bounds', [16, 32], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 25);

% Input resistance
varParams(5) = struct( ...
    'name', 'rin', ...
    'range', [1e3, 5e3], ...
    'bounds', [1e3, 5e3], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 2.4e3);

%% ------------------------------------------------------------------------
% ADC model parameters
% -------------------------------------------------------------------------

modelParams = struct();

% -------------------- System --------------------
modelParams.loopOrder          = 1;
modelParams.maxFoM             = 200;
modelParams.noiseFoldingEnable = 1;
modelParams.fsRes              = 50000;
modelParams.bwIterMethod       = 'fixed';
modelParams.bwIterations       = 50;

% -------------------- Input --------------------
modelParams.inputFreq = 661.5e3;
modelParams.minOsr    = 2;

% -------------------- Quantizer --------------------
modelParams.nMp  = 25; 

% -------------------- SFDR --------------------
modelParams.a1 = 1;
modelParams.a2 = 3.58e5*5e-5/(2*10^(3/20)); % a2 set to keep A2 3dB above A3
modelParams.a3 = 3.58e5; % Calculated from error node swing and 73dB SFDR

% -------------------- DAC --------------------
modelParams.sigmaI   = 2.2/100; % From paper
modelParams.idacUnit = 26e-6;

% -------------------- Power --------------------
modelParams.vddAfe    = 1.2;
modelParams.vddDig    = 0.7;
modelParams.vddVco    = 1.2;
modelParams.pVcoRef   = 1.5e-3;
modelParams.kVcoRef   = 200e9;
modelParams.pDigRef   = 0;
modelParams.fsRef     = 300e6;
modelParams.vddDigRef = 0.8;
modelParams.ibiasVco = 130e-6;
modelParams.T = 300;
modelParams.phiT = 0.025;
%% ------------------------------------------------------------------------
% ADC performance specifications
% -------------------------------------------------------------------------

spec = struct( ...
    'FOM',      168, ...
    'SNDR',     72, ...
    'P_TOT',    3e-3, ...
    'BW',       1e6, ...
    'IRN_FLOOR', 100e-12, ...
    'RIN',    2e3);

end
