function [varParams, modelParams, spec] = validationSet(subSet)
%validatinoSet Define validation parameter for the VCO-ADC model. 
% For use with the baseline model (evaluateAdcModel.m).
% Used for design walkthrough.
%%   INPUT:
%       subSet : Integer
%           Selects the subSet of variables, used to toggle between
%           validation and optimization
%           subSet = 0 --> Validation
%           subSet = 1 --> Optimization
%%   OUTPUT : 
% This function returns all configuration structures required to run
% validation and optimization for the analytical VCO-ADC model. It allows 
% clean, easily reproducible, swappable and expandable validation setups.
% The configuration is split into three logical groups:
%
%   1) varParams   : Design variables and their constraints
%   2) modelParams : ADC model configuration
%   3) spec        : Target ADC performance specifications

%% ------------------------------------------------------------------------
% Variable parameters 
% -------------------------------------------------------------------------

% Sampling frequency
varParams(1) = struct( ...
    'name', 'fs', ...
    'range', [32e3, 512e3], ...
    'bounds', [10e3, 10e6], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 128e3);

if(~subSet)
        % VCO gain : Fixed - For Validation
        varParams(2) = struct( ...
        'name', 'kVco', ...
        'range', [0.1e6, 100e6], ...
        'bounds', [0.1e6, 100e6], ...
        'analysisType', 'fixed', ...
        'sweepType', 'lin', ...
        'sweepLength', 50, ...
        'fixedValue', 50e6);
else
        % VCO gain : Surface - For Optimization
        varParams(2) = struct( ...
        'name', 'kVco', ...
        'range', [1e6, 100e6], ...
        'bounds', [1e6, 100e6], ...
        ...
        'analysisType', 'surface', ...
        'sweepType', 'lin', ...
        'sweepLength', 50, ...
        'fixedValue', '');
end

if(~subSet)   
    % Full-scale input voltage : Fixed - For Validation
    varParams(3) = struct( ...
        'name', 'vinFs', ...
        'range', [0.4, 1.8], ...
        'bounds', [0.4, 1.8], ...
        'analysisType', 'fixed', ...
        'sweepType', 'lin', ...
        'sweepLength', 50, ...
        'fixedValue', 1.2);
else
        % Full-scale input voltage : Fixed - For Validation
        varParams(3) = struct( ...
        'name', 'vinFs', ...
        'range', [0.4, 1.8], ...
        'bounds', [0.4, 1.8], ...
        'analysisType', 'surface', ...
        'sweepType', 'lin', ...
        'sweepLength', 50, ...
        'fixedValue', '');
end

% DAC resolution
varParams(4) = struct( ...
    'name', 'nDac', ...
    'range', [7, 13], ...
    'bounds', [7, 16], ...
    'analysisType', 'fixed', ...
    'sweepType', '', ...
    'sweepLength', '', ...
    'fixedValue', 10);

% % Input resistance
% varParams(5) = struct( ...
%     'name', 'rIn', ...
%     'range', [0.8e6, 0.8e6], ...
%     'bounds', [0.5e6, 1.5e6], ...
%     'analysisType', 'fixed', ...
%     'sweepType', '', ...
%     'sweepLength', '', ...
%     'fixedValue', 0.8e6);

%% ------------------------------------------------------------------------
% ADC model parameters
% -------------------------------------------------------------------------

modelParams = struct();

% -------------------- System --------------------
modelParams.loopOrder          = 1;
modelParams.nef                = 7;
modelParams.maxFoM             = 200;
modelParams.noiseFoldingEnable = 1;
modelParams.fsRes              = 50000;
modelParams.bwIterMethod       = 'fixed';
modelParams.bwIterations       = 5;

% -------------------- Input --------------------
modelParams.maxVinFs  = 1.8;
modelParams.inputFreq = 100;
modelParams.minOsr    = 2;

% -------------------- Quantizer --------------------
modelParams.nMp  = 1; 

% -------------------- SFDR --------------------
modelParams.a1 = 1;
modelParams.a2 = 0;
modelParams.a3 = 100;

% -------------------- DAC --------------------
modelParams.cdacUnit = 2e-15;
modelParams.sigmaC   = 0.6/100;
modelParams.maxVdd   = 1.8;
modelParams.cdacType = 0;

% -------------------- Power --------------------
modelParams.vddAfe    = 1.2;
modelParams.vddDig    = 0.8;
modelParams.pVcoRef   = 1.5e-6;
modelParams.kVcoRef   = 8e6;
modelParams.pDigRef   = 50e-9;
modelParams.fsRef     = 128e3;
modelParams.vddDigRef = 0.8;
modelParams.T = 300;
modelParams.phiT = 0.025;
%% ------------------------------------------------------------------------
% ADC performance specifications
% -------------------------------------------------------------------------

spec = struct( ...
    'FOM',      175, ...
    'SNDR',     85, ...
    'P_TOT',    10e-6, ...
    'BW',       1000, ...
    'IRN_FLOOR', 250e-9, ...
    'VIN_FS',    0.4);

end
