classdef Adc
%Adc  Container class for ADC design variables, configuration parameters,
%and performance.
%
%   The Adc class encapsulates the complete state of an ADC instance
%   generated by the modeling framework. It is intended
%   to serve as the primary data object passed between modelling,
%   optimization, and visualization routines. The class also provides 
%   utilities for formatted printing of numeric performance data. 
%
%   An Adc object stores:
%       - vars      : Design variables used to synthesize and optimize the ADC
%       - modelParams : Fixed ADC model parameters
%       - perf      : Primary performance metrics
%       - perfAux   : Auxiliary or intermediate performance metrics
%       - spec      : Target performance specifications
%
%   Typical usage:
%       adc = VOLTA.model.evaluateAdcModel(vars, modelParams, spec);
%       adc.printPerf();
%       adc.printPerfAux();


    properties
        vars        % Struct of design variables used to generate ADC
        modelParams   % Struct of ADC model parameters
        perf        % Struct of primary ADC performance metrics
        perfAux     % Struct of auxiliary performance metrics
        spec        % Struct of ADC targer performance specifications
    end

    methods
        %------------------------------------------------------------------
        % Constructor
        %------------------------------------------------------------------
        function obj = Adc(vars, adcParams, perf, perfAux, spec)
            %ADC Construct an Adc object
            %
            %   obj = Adc(vars, adcParams, perf, perfAux, spec)
            %
            %   All five inputs are required and stored directly.

            if nargin == 5
                obj.vars      = vars;
                obj.modelParams = adcParams;
                obj.perf      = perf;
                obj.perfAux   = perfAux;
                obj.spec      = spec;
            else
                fprintf("ERROR: Incorrect number of arguments to create Adc object.\n");
            end
        end

        %------------------------------------------------------------------
        % Helper: format numeric values using scientific notation (%.2e)
        %------------------------------------------------------------------
        function s = formatNumeric(~, value)
            %FORMATNUMERIC Format numeric scalars or arrays consistently
            %
            %   - Scalars are formatted as '%.2e'
            %   - Arrays are formatted row-wise
            %   - Complex values are formatted as (a+bi) with scientific notation

            % Handle complex-valued inputs
            if ~isreal(value)
                fmtElem = @(x) sprintf('(%s%+si)', ...
                    sprintf('%.2e', real(x)), ...
                    sprintf('%.2e', imag(x)));

                if isscalar(value)
                    s = fmtElem(value);
                else
                    rows = size(value, 1);
                    rowStrs = cell(1, rows);
                    for r = 1:rows
                        elems = arrayfun(fmtElem, value(r,:), 'UniformOutput', false);
                        rowStrs{r} = strjoin(elems, ' ');
                    end
                    s = ['[' strjoin(rowStrs, '; ') ']'];
                end
                return
            end

            % Real-valued numeric inputs
            if isscalar(value)
                s = sprintf('%.2e', value);
            else
                [nRows, ~] = size(value);
                rowStrs = cell(1, nRows);
                for r = 1:nRows
                    elems = arrayfun(@(x) sprintf('%.2e', x), ...
                                     value(r,:), 'UniformOutput', false);
                    rowStrs{r} = strjoin(elems, ' ');
                end
                s = ['[' strjoin(rowStrs, '; ') ']'];
            end
        end

        %------------------------------------------------------------------
        % Print primary performance structure
        %------------------------------------------------------------------
        function printPerf(obj)
            %PRINTPERF Display contents of perf structure

            fprintf("=== PERFORMANCE ===\n");

            if isempty(obj.perf)
                fprintf("(empty)\n");
                return
            end

            fields = fieldnames(obj.perf);
            for i = 1:numel(fields)
                fieldName = fields{i};
                value = obj.perf.(fieldName);

                if isnumeric(value)
                    fprintf("%s = %s\n", fieldName, obj.formatNumeric(value));

                elseif islogical(value)
                    fprintf("%s = %s\n", fieldName, mat2str(value));

                elseif ischar(value) || (isstring(value) && isscalar(value))
                    fprintf("%s = %s\n", fieldName, char(value));

                elseif isstring(value) && ~isscalar(value)
                    fprintf("%s = %s\n", fieldName, mat2str(cellstr(value)));

                elseif isstruct(value)
                    fprintf("%s = <struct>\n", fieldName);

                else
                    try
                        fprintf("%s = %s\n", fieldName, mat2str(value));
                    catch
                        fprintf("%s = <unprintable type: %s>\n", ...
                                fieldName, class(value));
                    end
                end
            end
        end

        %------------------------------------------------------------------
        % Print auxiliary performance structure
        %------------------------------------------------------------------
        function printPerfAux(obj)
            %PRINTPERFAUX Display contents of perfAux structure

            fprintf("=== PERFORMANCE AUXILIARY ===\n");

            if isempty(obj.perfAux)
                fprintf("(empty)\n");
                return
            end

            fields = fieldnames(obj.perfAux);
            for i = 1:numel(fields)
                fieldName = fields{i};
                value = obj.perfAux.(fieldName);

                if isnumeric(value)
                    fprintf("%s = %s\n", fieldName, obj.formatNumeric(value));

                elseif islogical(value)
                    fprintf("%s = %s\n", fieldName, mat2str(value));

                elseif ischar(value) || (isstring(value) && isscalar(value))
                    fprintf("%s = %s\n", fieldName, char(value));

                elseif isstring(value) && ~isscalar(value)
                    fprintf("%s = %s\n", fieldName, mat2str(cellstr(value)));

                elseif isstruct(value)
                    fprintf("%s = <struct>\n", fieldName);

                else
                    try
                        fprintf("%s = %s\n", fieldName, mat2str(value));
                    catch
                        fprintf("%s = <unprintable type: %s>\n", ...
                                fieldName, class(value));
                    end
                end
            end
        end
    end
end
